### ISSUE TITLE
Massive latency with simple pipeline

### ISSUE THREAD

**Issue by arr28** [DodgyJammers/jammypiece#5]
Even with a simple pipeline that's doing almost no processing, there's a massive (250ms+?) latency between pressing a note on the keyboard and hearing it via the synth.

**Comment by arr28** [comment]
http://www.sibeliusblog.com/tips/taming-the-flexi-time-latency-beast/ may help.

**Comment by arr28** [comment]
Actually, the latency was more like 500ms.  However, by using the OS synth (Microsoft MIDI Mapper Windows MIDI_MAPPER) instead of the Java synth (OpenJDK Gervill Software MIDI Synthesizer), I've got that down to ~250ms.

I wonder where the latency is occurring.

**Comment by arr28** [comment]
Hmm, well this is looking bad.  I gather (from MF & KSW) that the reviews say that the Roland UM-ONE is the best MIDI -> USB converter around, in terms of latency.  However, I've definitely got a latency issue here and it's somewhere during the input stage.

The pipeline is...

Keyboard -> USB Dongle -> USB port -> jammypiece in -> jammypiece out -> OS Synth -> headphones
- When I press a note on the keyboard, the little light on the USB dongle flashes immediately.  I don't know whether that's the USB dongle reporting receipt of a MIDI event or whether it's reporting that it has parcelled up the event and sent it over USB.
- The next debugging point is in Java.  As soon as I get an event, I print out a debug statement.  This accounts for nearly all of the latency.
- Within the skeleton jammypiece pipeline, there's less than 1ms latency.
- Between the final log from jammypiece (immediately before sending the output to the MIDI output framework) and hearing the sound, there's almost no delay.

So, the problem lies somewhere between the Roland device receiving the MIDI input and jammypiece receiving the same.  I've tried (a) switching off my VM, which sometimes interferes with this sort of thing and (b) using a different USB port.  If I squint at it funny, I can almost convince myself that the latter helped.  But really, it's still a big issue.

---

I'd like to try with somebody else's PC.  Also, if any of you have a MacBook or laptop running Linux, I'd definitely be interested to try that too.

Or maybe we need to get a serial connector after all.  No idea what drivers might be required to present that as a MIDI interface and whether it would actually help.

**Comment by kw217** [comment]
Easiest solution might be to develop on Linux rather than Windows. I set up the Roland UM-ONE mk2 and "rosegarden" (a MIDI editor) on my Ubuntu workstation at home, and connected it up to my Yamaha NP-31. With rosegarden set to loop MIDI back out to the device, but the device also playing on each key, I couldn't detect the latency - the two notes were sounding near-simultaneously.

However I've not tried with jammypiece yet - if Java has issues, that would still be a problem.

**Comment by rgefryer** [comment]
My previous MIDI processing has been in C on a 386sx DOS PC, then on a PalmPilot, and had no detectable latency.  Any latency will be a killer.

Just one thought - for a bit of fun, we could implement on a Raspberry Pi, the idea being that it might end up as being a standalone piece of hardware.

**Comment by arr28** [comment]
Phew.  As it transpires, it was output latency after all.  I was misled because the logging path also had high latency.

Sending the MIDI back out to a hardware synth solves the problem.  (There may also be lower latency soft synths and/or asio4all.)
